name: osm_nominatim
description: A library to perform OSM Nominatim searches also supporting reverse searches
version: 1.0.0
homepage: https://github.com/hamidweazi/osm-nominatim

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  # http: ^1.0.0
  http: ">=0.13.0 <2.0.0"

dev_dependencies:
  test: ^1.24.3
